name: Entregables

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: paso 1  Checkout repositorio
        uses: actions/checkout@v4

      - name: paso 2  Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.2"

      - name: paso 3  Crear entorno virtual
        run: python -m venv venv

      - name: paso 4  Activar el entorno virtual
        run: .\venv\Scripts\activate

      - name: paso 5  ejecutar script
        run: .\venv\Scripts\python hola.py







        
